version: "3"
services:
  db:
    image: postgres:9.6.3-alpine
    restart: always
    volumes:
      - ./PostgresAlpine/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - PostgresAlpine/db.env
  web:
    build: ./PayaraMicro
    ports:
      - "8080:8080"    
    depends_on:
      - db
