version: "3"
services:
  db:
    build: ./PostgresAlpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: ./PayaraMicro
    ports:
      - "8080:8080"    
    depends_on:
      - db
